name: 05-2-filters-activity-types.yaml
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Imprime uma mensagem
        run: echo "Running whenever a PR is closed"


